@startuml

participant App as APP
participant LinkLossService as LLS
participant BT_Stack as BTS
participant EventQueue as EQ

== Link Loss Service Constructed ==
LLS <- BTS : onConnectionComplete(event)
activate LLS

LLS -> LLS : stop_alert()

LLS -> EQ : cancel(x)
note left
0 < x
end note
activate EQ
deactivate EQ

LLS -> APP : on_alert_end()
deactivate LLS

@enduml
