@startuml
skinparam ParticipantPadding 40
skinparam BoxPadding 10

box "FOTA Target" #White
participant Application as app
participant EventHandler as eh
participant FOTAService as fotasvc
end box
participant FOTAClient as fotaclient

fotaclient -> fotasvc : Write Control: FOTA Start
fotasvc -> eh: on_control_written(FOTA Start)
eh -> app: Ready for FOTA?
app -> eh: Not ready
eh -> fotasvc: return AUTH_CALLBACK_REPLY_ATTERR_APP_BUSY
fotasvc -> fotaclient : ATT Write Error: AUTH_CALLBACK_REPLY_ATTERR_APP_BUSY
@enduml