@startuml
skinparam ParticipantPadding 40
skinparam BoxPadding 10

box "FOTA Target" #White
participant EventHandler as eh
participant FOTAService as fotasvc
end box
participant FOTAClient as fotaclient

fotaclient -> fotasvc : Write BSC (fragment ID = 255)
fotasvc -> fotasvc: check fragment ID = 255
fotasvc -> eh: on_bsc_written(data)
eh -> eh : Program BSC data into NV memory
fotaclient -> fotasvc: Write BSC (fragment ID = 0)
fotasvc -> fotasvc: check fragment ID = 0
fotasvc -> eh: on_bsc_written(data)
eh -> eh : Program BSC data into NV memory
@enduml